COQC       := coqc
COQDEP     := coqdep
OCAMLC     := ocamlc
OCAMLBUILD := ocamlbuild
CC         := gcc
CFLAGS     := -g
AR         := ar
SLINK      := ln -s -f
YNOT       := $(KRAKEN)/compiler/ynot/src/coq
OCAMLH     := $(shell $(OCAMLC) -where)

# path to root of generated kernel
KROOT := /home/daniel/Dropbox/PL/ssh/u-ssh

